CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE addendum
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    addendum_number VARCHAR(255),
    end_date        date,
    quantity        BIGINT,
    start_date      date,
    unit_price      BIGINT,
    contract_id     BIGINT,
    CONSTRAINT addendum_pkey PRIMARY KEY (id)
);

CREATE TABLE contract_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity    BIGINT,
    unit_price  BIGINT,
    contract_id BIGINT,
    product_id  BIGINT,
    CONSTRAINT contract_item_pkey PRIMARY KEY (id)
);

CREATE TABLE contracts
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    advance_payment      BIGINT,
    contract_description VARCHAR(255),
    contract_number      VARCHAR(255),
    end_date             date,
    insurance_deposit    BIGINT,
    performance_bond     BIGINT,
    start_date           date,
    customer_id          BIGINT,
    CONSTRAINT contracts_pkey PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_code VARCHAR(255),
    economic_code VARCHAR(255),
    name          VARCHAR(255),
    national_code VARCHAR(255),
    phone         VARCHAR(255),
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE invoice
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    due_date          date,
    invoice_number    BIGINT,
    issued_date       date,
    contract_id       BIGINT,
    invoice_status_id INTEGER,
    CONSTRAINT invoice_pkey PRIMARY KEY (id)
);

CREATE TABLE invoice_item
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity             INTEGER,
    unit_price           BIGINT,
    invoice_id           BIGINT,
    product_id           BIGINT,
    warehouse_receipt_id BIGINT,
    CONSTRAINT invoice_item_pkey PRIMARY KEY (id)
);

CREATE TABLE invoice_status
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT invoice_status_pkey PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_amount      FLOAT8,
    payment_date        date,
    payment_descryption VARCHAR(255),
    customer_id         BIGINT,
    CONSTRAINT payment_pkey PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_index VARCHAR(255)                            NOT NULL,
    product_code      VARCHAR(255),
    product_name      VARCHAR(255),
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE report
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_date        date,
    report_explanation VARCHAR(255),
    CONSTRAINT report_pkey PRIMARY KEY (id)
);

CREATE TABLE report_item
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity             INTEGER,
    unit_price           BIGINT,
    customer_id          BIGINT,
    report_id            BIGINT,
    warehouse_receipt_id BIGINT,
    CONSTRAINT report_item_pkey PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH ۴) NOT NULL,
    name VARCHAR(20),
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH ۲) NOT NULL,
    email    VARCHAR(50),
    password VARCHAR(120),
    username VARCHAR(20),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE warehouse_receipt
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    warehouse_receipt_date        date,
    warehouse_receipt_description VARCHAR(255),
    warehouse_receipt_number      BIGINT,
    customer_id                   BIGINT,
    CONSTRAINT warehouse_receipt_pkey PRIMARY KEY (id)
);

CREATE TABLE warehouse_receipt_item
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity             INTEGER,
    unit_price           BIGINT,
    product_id           BIGINT,
    warehouse_receipt_id BIGINT,
    CONSTRAINT warehouse_receipt_item_pkey PRIMARY KEY (id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

CREATE TABLE company_reportdto
(
    id                  BIGINT NOT NULL,
    amount              BIGINT,
    avg_unit_price      BIGINT,
    cumulative_quantity BIGINT,
    name                VARCHAR(255),
    quantity            BIGINT,
    CONSTRAINT company_reportdto_pkey PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    user_id BIGINT  NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE users_roles
    ADD CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE warehouse_receipt_item
    ADD CONSTRAINT fk5orcdhr7ntv5q0rdvfrxesgbl FOREIGN KEY (warehouse_receipt_id) REFERENCES warehouse_receipt (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE report_item
    ADD CONSTRAINT fk8i683i9cl4l46ev3r8fmrjaaa FOREIGN KEY (warehouse_receipt_id) REFERENCES warehouse_receipt (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE addendum
    ADD CONSTRAINT fk_addendum__contract FOREIGN KEY (contract_id) REFERENCES contracts (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE contracts
    ADD CONSTRAINT fk_contract__customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice__contract FOREIGN KEY (contract_id) REFERENCES contracts (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice__invoice_status FOREIGN KEY (invoice_status_id) REFERENCES invoice_status (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE invoice_item
    ADD CONSTRAINT fk_invoice_item__invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE invoice_item
    ADD CONSTRAINT fk_invoice_item__product FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE payment
    ADD CONSTRAINT fk_payment__customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE report_item
    ADD CONSTRAINT fk_report_item__customer FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE report_item
    ADD CONSTRAINT fk_report_item__report FOREIGN KEY (report_id) REFERENCES report (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE warehouse_receipt_item
    ADD CONSTRAINT fk_warehouse_receipt_item__product FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE contract_item
    ADD CONSTRAINT fkbussrkh7kcrouvmtr3b0eqv88 FOREIGN KEY (contract_id) REFERENCES contracts (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE contract_item
    ADD CONSTRAINT fkgnt2scdktv14sxl9jddjmfm3v FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE invoice_item
    ADD CONSTRAINT fkj5rut99dekmughf5efd357swj FOREIGN KEY (warehouse_receipt_id) REFERENCES warehouse_receipt (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_roles
    ADD CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id) REFERENCES roles (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE warehouse_receipt
    ADD CONSTRAINT fklc3cndqd08ho424dauubrnl48 FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;